// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4AcIp76dHPiZuKE4dVLdkNi61qf4WIIA',
    appId: '1:246295181939:web:bbf85cc2e41ff028308806',
    messagingSenderId: '246295181939',
    projectId: 'appmobile-4d354',
    authDomain: 'appmobile-4d354.firebaseapp.com',
    storageBucket: 'appmobile-4d354.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1xtuFlNcr-S-CSujzBWHd9YbS1_4sUCc',
    appId: '1:246295181939:android:2d38beb0a1adff79308806',
    messagingSenderId: '246295181939',
    projectId: 'appmobile-4d354',
    storageBucket: 'appmobile-4d354.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS5gOl7hlH6upyYQJXySe4rlHAaLGMlmc',
    appId: '1:246295181939:ios:d16f4588fbbecd21308806',
    messagingSenderId: '246295181939',
    projectId: 'appmobile-4d354',
    storageBucket: 'appmobile-4d354.firebasestorage.app',
    iosBundleId: 'com.example.precificadorIaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS5gOl7hlH6upyYQJXySe4rlHAaLGMlmc',
    appId: '1:246295181939:ios:d16f4588fbbecd21308806',
    messagingSenderId: '246295181939',
    projectId: 'appmobile-4d354',
    storageBucket: 'appmobile-4d354.firebasestorage.app',
    iosBundleId: 'com.example.precificadorIaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4AcIp76dHPiZuKE4dVLdkNi61qf4WIIA',
    appId: '1:246295181939:web:557a5ac767f27dc7308806',
    messagingSenderId: '246295181939',
    projectId: 'appmobile-4d354',
    authDomain: 'appmobile-4d354.firebaseapp.com',
    storageBucket: 'appmobile-4d354.firebasestorage.app',
  );

}